<div class="page-header">
    <h1><small>Doctor</small> <?=$this->doctor->getName() . ' ' . $this->doctor->getSurname()?></h1>
</div>
<?php
    echo $this->partial('clinic/generic/practitioner/all.phtml', [
        'practitioners' => $this->doctor->getPractitioners()
    ]);
    echo $this->partial('clinic/generic/appointment/all.phtml', [
        'appointments' => $this->doctor->getAppointments()
    ]);
?>
