<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-user"></span> Practitioners
        </h3>
    </div>
    <table class="table table-condensed table-striped table-hover">

    <!-- Headers -->
    <thead>
        <tr>
            <th>#</th>
            <th><span class="glyphicon glyphicon-pencil"></span> Joined</th>
            <th><span class="glyphicon glyphicon-info-sign"></span> Surname</th>
            <th><span class="glyphicon glyphicon-info-sign"></span> Name</th>
            <th><span class="glyphicon glyphicon-calendar"></span> Appointments</th>
            <th><span class="glyphicon glyphicon-user"></span> Supervisor</th>
            <th><span class="glyphicon glyphicon-envelope"></span> Email</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
    </thead>

<?php foreach($this->practitioners as $practitioner): ?>
<!-- Data -->
    <tr>
        <td> <?= $practitioner->getId() ?> </td>
        <td> <?= $practitioner->getJoined()->format('d M Y') ?></td>
        <td> <?= $practitioner->getSurname() ?> </td>
        <td> <?= $practitioner->getName() ?> </td>
        <td>
            <a href="
                <?= $this->url('admin', array(
                        'controller' => 'practitioner',
                        'action'     => 'appointments',
                        'id'         => $practitioner->getId()
                    ));
                ?>">View Appointments
            </a>
        </td>
        <td><a href="">View Supervisor</a></td>
        <td> <a href="mailto:<?= $practitioner->getEmail() ?> ">Send Email</a> </td>
        <td>
            <a href="#"><span class="glyphicon glyphicon-edit"></span>  Edit</a>
        </td>
        <td>
            <a href="#"><span class="glyphicon glyphicon-remove"></span>  Delete</a>
        </td>
    </tr>

<?php endforeach; ?>

</table>
<div class="panel-footer" align="center">No more practitioners</div>
</div>