<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-user"></span> Practitioners
        </h3>
    </div>
    <table class="table table-striped table-hover">

    <!-- Headers -->
    <thead>
        <tr>
            <th>#</th>
            <th><span class="glyphicon glyphicon-pencil"></span> Joined</th>
            <th><span class="glyphicon glyphicon-info-sign"></span> Name</th>
            <th><span class="glyphicon glyphicon-info-sign"></span> Surname</th>
            <th><span class="glyphicon glyphicon-user"></span> Supervisor</th>
            <th></th>
        </tr>
    </thead>

<?php foreach($this->practitioners as $practitioner): ?>
<!-- Data -->
    <?php
        $supervisor = $practitioner->getSupervisor();
        $supervisorUrl = $this->url('admin', [
            'controller' => 'doctor', 'action' => 'profile','id' => $supervisor->getId()
        ]);
        $profileUrl = $this->url('admin', [
            'controller' => 'practitioner', 'action' => 'profile','id' => $practitioner->getId()
        ]);
        $editUrl = $this->url('admin', [
            'controller' => 'practitioner', 'action' => 'edit', 'id' => $practitioner->getId()
        ]);
        $deleteUrl = $this->url('admin', [
            'controller' => 'practitioner', 'action' => 'delete', 'id' => $practitioner->getId()
        ]);
    ?>
    <tr>
        <td> <?= $practitioner->getId() ?> </td>
        <td> <?= $practitioner->getJoined()->format('d M Y') ?></td>
        <td> <?= $practitioner->getName() ?> </td>
        <td> <?= $practitioner->getSurname() ?> </td>
        <td><a href="<?= $supervisorUrl ?>"><span class="glyphicon glyphicon-user"></span>
            <?= $supervisor->getName() . ' ' . $supervisor->getSurname() ?></a></td>
        <td align="right">
            <div class="btn-group">
                <a class="btn btn-default btn-xs" href="<?= $profileUrl ?>#appointments">
                    <span class="glyphicon glyphicon-calendar"></span>
                    <span class="label label-warning"><?= $practitioner->getAppointments()->count() ?></span>
                    Appointments </a>
                <a class="btn btn-default btn-xs" href="<?= $profileUrl ?>">
                    <span class="glyphicon glyphicon-list-alt"></span>  Profile</a>
                <a class="btn btn-default btn-xs" href="mailto:<?= $practitioner->getEmail() ?>">
                    <span class="glyphicon glyphicon-envelope"></span> Email</a>
                <a class="btn btn-default btn-xs" href="<?= $editUrl ?>">
                    <span class="glyphicon glyphicon-edit"></span>  Edit</a>
                <a class="btn btn-default btn-xs" href="<?= $deleteUrl ?>">
                    <span class="glyphicon glyphicon-remove"></span>  Delete</a>
            </div>
        </td>
    </tr>

<?php endforeach; ?>

</table>
<div class="panel-footer" align="center">No more practitioners</div>
</div>