<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-calendar"></span> Appointments
        </h3>
    </div>
    <table class="table table-condensed table-striped table-hover">
    <!-- Headers -->
        <thead>
            <tr>
                <th>#</th>
                <th><span class="glyphicon glyphicon-calendar"></span> Date</th>
                <th><span class="glyphicon glyphicon-time"></span> Time</th>
                <th><span class="glyphicon glyphicon-user"></span> Patient</th>
                <th><span class="glyphicon glyphicon-user"></span> Practitioner</th>
                <th><span class="glyphicon glyphicon-user"></span> Doctor</th>
                <th><span class="glyphicon glyphicon-question-sign"></span> Visited</th>
                <th><span class="glyphicon glyphicon-question-sign"></span> Confirmed</th>
                <th><!-- Edit --></th>
                <th><!-- Delete--></th>
            </tr>
        </thead>
    <?php foreach($this->appointments as $appointment): ?>
    <!-- Data -->
        <?php
        $dateObj    = $appointment->getDate();
        $date       = [
            'd' => $dateObj->format('d'),
            'm' => $dateObj->format('M'),
            'y' => $dateObj->format('Y'),
        ];
        $time       = $dateObj->format('H:i');
        $patient    = $appointment->getPatient();
        $practitioner = $appointment->getPractitioner();
        $doctor     = $appointment->getDoctor();
        $yesIcon    = '<span class="glyphicon glyphicon-ok"></span>';
        $noIcon     = '<span class="glyphicon glyphicon-remove"></span>';
        $missed     = ($appointment->getMissed())? $yesIcon : $noIcon;
        $confirmed  = ($appointment->getConfirmed())? $yesIcon : $noIcon;
        $editUrl    = $this->url('admin', ['controller' => 'appointment', 'action' => 'edit',   'id' => $id]);
        $deleteUrl  = $this->url('admin', ['controller' => 'appointment', 'action' => 'delete', 'id' => $id]);
        $patientUrl = $this->url('admin', ['controller' => 'patient',     'action' => 'index',  'id' => $id]);
        $doctorUrl  = $this->url('admin', ['controller' => 'doctor',      'action' => 'index',  'id' => $id]);
        $practitionerUrl = $this->url('admin', ['controller' => 'practitioner','action' => 'index', 'id' => $id]);
        echo "
        <tr>
            <td>{$appointment->getId()}</td>
            <td><strong>{$date['d']} {$date['m']}</strong> {$date['y']}</td>
            <td>{$time}</td>
            <td><a href='{$patientUrl}'>{$patient->getName()} {$patient->getSurname()}</a></td>
            <td><a href='{$practitionerUrl}'>{$practitioner->getName()} {$practitioner->getSurname()}</a></td>
            <td><a href='{$doctorUrl}'>{$doctor->getName()} {$doctor->getSurname()}</a></td>
            <td>{$missed}</td>
            <td>{$confirmed}</td>
            <td>
                <a href='{$editUrl}'><span class='glyphicon glyphicon-edit'></span>  Edit</a>
            </td>
            <td>
                <a href='{$deleteUrl}'><span class='glyphicon glyphicon-remove'></span>  Delete</a>
            </td>
        </tr>
        ";
    ?>
    <?php endforeach; ?>
    </table>
    <div class="panel-footer" align="center">No more appointments</div>
</div>