<div class="page-header">
    <h1>Appointment</h1>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">Complaints and Feedback</h3></div>
    <ul class="list-group">
        <li class="list-group-item">
            <h4 class="list-group-item-heading">Patient's complaints</h4>
            <p class="list-group-item-text"><?= $appointment->getComplaints() ?></p>
        </li>
        <li class="list-group-item">
            <h4 class="list-group-item-heading">Patient's feedback</h4>
            <p class="list-group-item-text"><?= $appointment->getPatientFeedback() ?></p>
        </li>
        <li class="list-group-item">
            <h4 class="list-group-item-heading">Doctor's feedback</h4>
            <p class="list-group-item-text"><?= $appointment->getDoctorFeedback() ?></p>
        </li>
        <li class="list-group-item">
            <h4 class="list-group-item-heading">Practitioner's feedback</h4>
            <p class="list-group-item-text"><?= $appointment->getPractitionerFeedback() ?></p>
        </li>
    </ul>
</div>