<?php if(!empty($this->appointments)): ?>
    <div class="table-responsive">
        <table class="table table-condensed table-striped table-hover">
        <!-- Headers -->
            <thead>
                <tr>
                    <th>#</th>
                    <th><span class="glyphicon glyphicon-calendar"></span> Date</th>
                    <th><span class="glyphicon glyphicon-time"></span> Time</th>
                    <th><span class="glyphicon glyphicon-user"></span> Patient</th>
                    <th><span class="glyphicon glyphicon-user"></span> Practitioner</th>
                    <th><span class="glyphicon glyphicon-user"></span> Doctor</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
        <?php foreach($this->appointments as $appointment) {
            echo $this->partial('clinic/generic/appointment/row.php', [
                'appointment' => $appointment
            ]);
        } ?>
        </table>
    </div>
<?php else: ?>
    <div class="panel-footer" align="center">No appointments</div>
<?php endif; ?>