<script type="text/javascript">
    $(document).ready(function () {
        var delay = 5000;
        setTimeout(function(){ window.location.href = "<?=$this->url?>"; }, delay);
    });
</script>
<div class="panel panel-danger">
    <div class="panel-heading"><h3 class="panel-title">Error</h3></div>
     <div class="panel-body"><?=$message?></div>
    <div class="panel-footer">
        You are being redirected back to <a href="<?=$this->url?>">the previous page</a>
    </div>
</div>