<script type="text/javascript">
    $(document).ready(function () {
        var delay = 5000;
        setTimeout(function(){ window.location.href = "<?=$this->url?>"; }, delay);
    });
</script>
<div class="panel panel-success">
    <div class="panel-heading"><h3 class="panel-title">Success</h3></div>
     <div class="panel-body"><?=$message?></div>
    <div class="panel-footer">
        You are being redirected <a href="<?=$this->url?>">Click here if you are not redirected</a>
    </div>
</div>